### PR TITLE
Made entire issue card clickable and added hover efect to the time

### PR DESCRIPTION
**Pull request by SpatzlHD**
# PR Template 🚀

## 🐛 Fixed Issue
This is a soulution for issue #52

## 🛠 Proposed Changes

I made the entire issue card clickable and redirect to the issue page. And now when you hover over a card the time the issue was created shows up.

## 🖼️ Screenshots

Recording 2023-10-08 at 14 48 12

## Checklist ✅

- [x] All tests pass successfully.
- [x] Code adheres to the project's coding standards.
- [x] Documentation is updated to reflect the changes.
- [x] No sensitive information is inadvertently exposed.
- [x] Commit history is clear and concise.

### CODE REVIEW

**Review by anand346 — APPROVED** [review]
approving these changes

**Comment by anand346** [comment]
Hi @SpatzlHD, could you please remove that time changing feature. The issue's time is not matching with different timezone. I'm attaching a video kindly take a look. Just leave the time as it was before. Thanks

https://github.com/anand346/findissues/assets/64061582/572d065f-2592-4bbf-80cf-d0010d08b504

**Comment by SpatzlHD** [comment]
> Hi @SpatzlHD, could you please remove that time changing feature. The issue's time is not matching with different timezone. I'm attaching a video kindly take a look. Just leave the time as it was before. Thanks

Yea that's true! Tbh I thought about it already but then just said f it let's unite the world in UTC. But I understand that this is a not so good approach! I will revert this change back.

**Comment by SpatzlHD** [comment]
@anand346 this should remove the time feature

**Pull request merged**
