### PR TITLE
Just Adding the apk file of Findissues Android Application

### PR DESCRIPTION
**Pull request by Dhruvdangi03**
**Enhancement**
Made a simple application that we can use from our phone when we don't have our laptop with us.

### CODE REVIEW

**Comment by SpatzlHD** [comment]
I think it would be better to just open the repo link in the default browser. Because you first of all are not logged in to GitHub what is really annoying when you want to comment on the issue and the other thing is you can't use passkeys as a login method when using your in App browser version of GitHub. But other than that I like it 👍

**Comment by SpatzlHD** [comment]
And I don't know to really explain but there is this strange behaviour that when starting the app it shows issues who were created recently **but** not ass recently as the website shows them so for example when the most recent issue in the app is 8 minutes ago the most recent one on the website is 4 minutes ago. But what the real problem ist that when you click on a issue and then go back to the app all issues that are shown are from 1 day ago. Here is a video:

https://github.com/anand346/findissues/assets/79466158/427f7763-33f4-47bb-945c-b411d2e0298f

And the second thing is that I think it would be great if we could have something to reload the page like in the browser so just pull down to reload and show newer issues.

**Comment by Dhruvdangi03** [comment]
I will try to fix it 👍

**Comment by Dhruvdangi03** [comment]
@SpatzlHD I have fixed the issues that you have told me can you now take a look at the apk file ?

**Comment by SpatzlHD** [comment]
> @SpatzlHD I have fixed the issues that you have told me can you now take a look at the apk file ?

I will take a look at it in something like 4 hours!

**Review by anand346 — APPROVED** [review]
I'm approving these changes

**Pull request merged**
