### PR TITLE
load issues whose repo has >= 100 stars or forks

### PR DESCRIPTION
**Pull request by KrishavRajSingh**
…stars >= 100

# PR Template 🚀

## 🐛 Fixed Issue #6 
while loading the repo, repos with 0 stars and forks were also been loaded
Issue link: https://github.com/anand346/findissues/issues/6

## 🛠 Proposed Changes
I made a check on the star and fork on the repo and only added it to the issue list if either of the repo or stars were >= 100

## 🖼️ Screenshots
image
image

## Checklist ✅
- [✅ ] All tests pass successfully.
- [✅ ] Code adheres to the project's coding standards.
- [ ✅] Documentation is updated to reflect the changes.
- [ ✅] No sensitive information is inadvertently exposed.
- [ ✅] Commit history is clear and concise.

### CODE REVIEW

**Comment by anand346** [comment]
Hi @KrishavRajSingh , glad to see that you've put your efforts in resolving this issue. Actually the goal is to show **30 issues total** on a page but the respective repo of all the issues should not have 0 stars. Star count can be greater than 10 or 20 per repo. Thanks

**Comment by KrishavRajSingh** [comment]
> Hi @KrishavRajSingh , glad to see that you've put your efforts in resolving this issue. Actually the goal is to show **30 issues total** on a page but the respective repo of all the issues should not have 0 stars. Star count can be greater than **10 or 20 per repo** and there must be total of 30 issues on a single page. Thanks

1> So the main goal is to get 30 issues per page, right??

2> Let's say there are total 25 issues including the 0 star repo, should I include it or remove it from the final list??

**Comment by anand346** [comment]
Let's say there are 100 total issue per page right including 0 star repo. The main goal is to show only 30 issues from the top which have >= 10 or 20 stars. 

The point here is, the API call in this project hasn't defined how many issues to fetch, so by default it is fetching only 30 issues including 0 star repo and to fetch 100 issues you need to specify the parameter in the API endpoint (you can check the github API documentation).

**Comment by KrishavRajSingh** [comment]
> Let's say there are 100 total issue per page right including 0 star repo. The main goal is to show only 30 issues from the top which have >= 10 or 20 stars.
> 
> The point here is, the API call in this project hasn't defined how many issues to fetch, so by default it is fetching only 30 issues including 0 star repo and to fetch 100 issues you need to specify the parameter in the API endpoint (you can check the github API documentation).

I am facing issue while adding a query for stars:>10 in the url.
It don't get the expected response from the github api.

**Comment by anand346** [comment]
Github API doesn't filter issues on the basis of stars and forks.

**Comment by KrishavRajSingh** [comment]
> Github API doesn't filter issues on the basis of stars and forks but it does filtering of repo on the basis of stars and forks

Hey can you help me bit, I am not getting on how to solve this issue.
I am thinking of creating a button which will sort the 30 issues in the list on the basis of stars after fetching them.
If you have any other approach, do share with me.

**Pull request closed without merging**
