### PR TITLE
feat: issuesCard - update time elapsed since issue creation regularly

### PR DESCRIPTION
**Pull request by lokesh-veerappan-47**
## 🐛 Fixed Issue #49 
[Issue Link](https://github.com/anand346/findissues/issues/49)

## 🛠 Proposed Changes
In the issues card component we are introducing regular updating of time elapsed since issue creation. It's updated at an interval of 30 seconds.
screenshot

## 📝 Notes for Reviewers
The interval of 30 seconds should be good enough for this use case. We can increase it to 60 seconds if we notice a hit on performance and need to reduce the amount of re-renders by half. But on local testing there was hardly any change in rendering performance.

### CODE REVIEW

**Review by anand346 — APPROVED** [review]
I'm approving these changes

**Comment by anand346** [comment]
Hi @lokesh-veerappan-47, actually there's a bug arised in updation of issue creation time. The issue time is showing `an hour ago` while it was created `45 minutes ago`. I'm attaching a video kindly have a look

https://github.com/anand346/findissues/assets/64061582/e9f8146b-f42b-4772-90dc-a331e6094d34

**Comment by anand346** [comment]
I'm reverting this PR feel free to raise a PR when you are done.

**Comment by lokesh-veerappan-47** [comment]
@anand346 I have reproduced the issue. This bug has nothing to do with the previous PR. This is an issue with the package that we are using to calculate the time elapsed. Sop this issue would have been present even before we implemented this enhancement.
The getTimeFromNow() function that was already present in the codebase is using moment library to do this. The fromNow() function from that library is creating this inconsistency. Github is probably calculating this in a fine grained manner and momentjs doesn't. We need to either write our own code for this or find another package that is consistent with github's implementation.
You can apply the previous PR back again, and raise a separate bug for this issue. I can take that up.

**Comment by lokjaw** [comment]
@anand346 check out PR https://github.com/anand346/findissues/pull/53

**Pull request merged**
