### PR TITLE
Feat : Add scroll to top

### PR DESCRIPTION
**Pull request by Peteredwardj**
# PR Template 🚀

## 🐛 Fixed Issue

Resolves [43](https://github.com/anand346/findissues/issues/43)

## 🛠 Proposed Changes

- Add a "Scroll to top" button on the bottom right of the results page, clicking it will scroll to the top 

## 🖼
Screenshot 2023-12-06 at 2 52 41 AM
https://www.loom.com/share/83c2201c461f44ff96dfec16f5f41405 (note: sometimes the video won't play/freezes)

## 📝 Notes for Reviewers

- Don't know what the design of the button should look like, but I'm using the same styles currently in the repo. 
- I'm not too familiar with front-end development, so please let me know if I need to make changes! 

## Checklist ✅

- [x] Starred this repo ⭐.
- [x] Code adheres to the project's coding standards 💻.
- [x] No sensitive information is inadvertently exposed 👀.
- [x] Commit history is clear and concise 📃.

### CODE REVIEW

**Comment by anand346** [comment]
Hi @Peteredwardj, there's a minor fix in the PR. Can you please make the button visible only when the user scrolls to some points. And would you mind improving the button style a bit more, like giving the border of 2px of that yellow shade after removing the background color and the icon stroke to 5px, something like that. Thanks

**Comment by Peteredwardj** [comment]
Hi @anand346, for sure I can change the style. 

Regarding the visibility of the button though, at which point do you think it should be visible? 

I guess it's a bit difficult to determine when exactly we can show it because the user could be in the middle of the list on a larger window but on a smaller window they might be 3 issues deep and the button is expected to show. Please let me know if you have any ideas and I can work on it.

**Comment by Peteredwardj** [comment]
Hi @anand346 , made the changes!

https://www.loom.com/share/f518a09342064c9fa654ef0c5fb56b4e?sid=d8698781-7a72-41f2-9aa5-88040c21ef72

Screenshot 2023-12-07 at 12 45 39 AM

**Comment by anand346** [comment]
That looks good

**Comment by Peteredwardj** [comment]
> That looks good

Awesome, thanks for letting me work on this issue!

**Pull request merged**
