### PR TITLE
Add sorting functionality to Search page

### PR DESCRIPTION
**Pull request by Yash636261**
# PR Template 🚀

## 🐛 Fixed Issue

Added the functionality of sorting. solving the issue #92

## 🛠 Proposed Changes

- Added sorting functionality to the search results page.
- Implemented sorting functions for various criteria.
- Updated the UI to include a dropdown for selecting the sorting option.

## 🖼️ Screenshots

image

image

## Checklist ✅

- [✅] Starred this repo ⭐.
- [✅] Code adheres to the project's coding standards 💻.
- [✅] No sensitive information is inadvertently exposed 👀.
- [✅] Commit history is clear and concise 📃.

### CODE REVIEW

**Comment by Yash636261** [comment]
I have completed the work. @anand346 , you can review and merge it.

**Review by anand346 — APPROVED** [review]
I'm approving these changes

**Comment by anand346** [comment]
Hi @Yash636261, I appreciate your valuable contribution. Can you please do a minor change, actually currently when someone clicks anywhere outside of opened popup then the popup is not closing. Can you please close the popup when someone clicks anywhere outside, it would be better. Thanks!

**Comment by Yash636261** [comment]
@anand346 check it out.

**Pull request merged**
