### PR TITLE
added new links for repos

### PR DESCRIPTION
**Pull request by cheta-nyadav**
# PR Template 🚀

## 🐛 Fixed Issue

Added new links for active repositories.

## 🛠 Proposed Changes

there are new added links for active repos where we can contribute to open source.

## 🖼️ Screenshots

Include relevant screenshots or GIFs showcasing the visual impact of the changes. Visual aids can significantly assist reviewers.

## 📝 Notes for Reviewers

Share additional insights or considerations for reviewers. This could encompass design decisions, potential side effects, or critical areas that require attention.

## Checklist ✅

- [x] Starred this repo ⭐.
- [x] Code adheres to the project's coding standards 💻.
- [x] No sensitive information is inadvertently exposed 👀.
- [x] Commit history is clear and concise 📃.

## Reviewer Tasks 🕵️

Specify any particular tasks or requests for reviewers to focus on during their assessment.

## Additional Context ℹ️

Add any pertinent information or context about the PR that may aid understanding.

### CODE REVIEW

**Comment by cheta-nyadav** [comment]
@anand346 can you review and authorize it please.

**Comment by anand346** [comment]
Hi @cheta-nyadav kindly check all the checklist checkboxes first

**Comment by cheta-nyadav** [comment]
> # PR Template 🚀
> ## 🐛 Fixed Issue
> Added new links for active repositories.
> 
> ## 🛠 Proposed Changes
> there are new added links for active repos where we can contribute to open source.
> 
> ## 🖼️ Screenshots
> Include relevant screenshots or GIFs showcasing the visual impact of the changes. Visual aids can significantly assist reviewers.
> 
> ## 📝 Notes for Reviewers
> Share additional insights or considerations for reviewers. This could encompass design decisions, potential side effects, or critical areas that require attention.
> 
> ## Checklist ✅
> * [x]  Starred this repo ⭐.
> * [x]  Code adheres to the project's coding standards 💻.
> * [x]  No sensitive information is inadvertently exposed 👀.
> * [x]  Commit history is clear and concise 📃.
> 
> ## Reviewer Tasks 🕵️
> Specify any particular tasks or requests for reviewers to focus on during their assessment.
> 
> ## Additional Context ℹ️
> Add any pertinent information or context about the PR that may aid understanding.

**Comment by cheta-nyadav** [comment]
@anand346 done!

**Comment by anand346** [comment]
Hi @cheta-nyadav, your submitted repo links does not meet the [criteria](https://github.com/anand346/findissues/blob/main/list-active-repo.md#criteria) of active repos. Kindly submit repo links which match the criteria of active repos

**Pull request closed without merging**
