### PR TITLE
Enhancement/update issue creation time

### PR DESCRIPTION
**Pull request by lokjaw**
🐛 Fixed Issue https://github.com/anand346/findissues/issues/49
https://github.com/anand346/findissues/issues/49

🛠 Proposed Changes
In the issues card component we are introducing regular updating of time elapsed since issue creation. It's updated at an interval of 30 seconds.
screenshot.
The calculation logic for time elapsed since issue creation has been updated. The previous calculation was done through a utility function from moment.js which was inconsistent with github's calculation on the same. Now we have our own logic implemented for this.

📝 Notes for Reviewers
The interval of 30 seconds should be good enough for this use case. We can increase it to 60 seconds if we notice a hit on performance and need to reduce the amount of re-renders by half. But on local testing there was hardly any change in rendering performance.

The calculated time elapsed is still a little different from what github will display on their issue page. 
For example when it has been 56 minutes since issue creation, our code will show it accurately as "56 minutes ago" but github's issue page will show it as "1 hour ago".  Github is rounding it up.

### CODE REVIEW

**Comment by lokjaw** [comment]
@anand346 check the last part of the notes above and we can discuss if we want to change this to make it more consistent with github.

**Comment by lokjaw** [comment]
@anand346 this closes issue #54

**Review by anand346 — APPROVED** [review]
I'm approving these changes

**Comment by anand346** [comment]
Your contribution is highly appreciable @lokjaw ✨. I've merged this PR

**Pull request merged**
